export const DEFAULT_THEME = {
  cellPaddingBottom: 2,
  cellPaddingLeft: 4,
  cellPaddingRight: 4,
  cellPaddingTop: 2,
  colheaderBackground: "#363636",
  colheaderForeground: "#ccc",
  rowEvenBackground: "#2c2c2c",
  rowEvenForeground: "#ccc",
  gridline: "#aaa",
  rowOddBackground: "#242424",
  rowOddForeground: "#ccc",
  fontFamily: "New York Medium",
  fontSize: 14,
  fontWeight: 400,
  fontString: "400 14px 'New York Medium'",
  lineHeight: 1.42,
};
